"""

Q280: The part of your code where the
handling of an exception takes
place should be placed inside:



Answer: the except: branch




"""